"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, Globe, Eye, RefreshCw } from "lucide-react";
import Link from "next/link";
import SitePreview from "@/components/SitePreview";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";

interface GeneratedSite {
  user_id: string;
  brand_name: string;
  category: string;
  tone: string;
  intro: string;
  compiled_html: string;
}

export default function ExplorePage() {
  const [sites, setSites] = useState<GeneratedSite[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedSite, setSelectedSite] = useState<GeneratedSite | null>(null);

  useEffect(() => {
    async function loadSites() {
      try {
        const res = await fetch("/api/explore");
        if (res.ok) {
          const data = await res.json();
          setSites(data);
        }
      } catch (err) {
        console.error("Failed loading community showcase:", err);
      } finally {
        setLoading(false);
      }
    }
    loadSites();
  }, []);

  return (
    <div className="min-h-screen bg-background text-foreground p-6 transition-colors duration-200">
      <div className="max-w-7xl mx-auto space-y-6">
        
        <div className="flex items-center justify-between border-b pb-4">
          <div className="space-y-1">
            <h1 className="text-2xl font-black tracking-tight">Community Showcase</h1>
            <p className="text-sm text-muted-foreground">
              Explore landing pages generated by other creators inside Formulate.
            </p>
          </div>
          {/* <Link href="/">
            <Button variant="outline" size="sm" className="gap-1.5">
              <ArrowLeft className="h-4 w-4" /> Back to Builder
            </Button>
          </Link> */}
        </div>

        {loading && (
          <div className="h-64 flex flex-col items-center justify-center text-muted-foreground">
            <RefreshCw className="h-8 w-8 animate-spin mb-2 text-primary" />
            <p className="text-sm font-medium">Loading community generations...</p>
          </div>
        )}

        {!loading && sites.length === 0 && (
          <div className="text-center py-20 border border-dashed rounded-xl text-muted-foreground bg-muted/10">
            <Globe className="h-10 w-10 mx-auto mb-3 stroke-1 animate-pulse text-muted-foreground" />
            <p className="font-medium text-sm">No public websites have been compiled yet.</p>
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {sites.map((site, index) => (
            <Card key={index} className="flex flex-col justify-between shadow-sm hover:shadow-md transition-all duration-200 bg-card">
              <CardHeader className="pb-3">
                <div className="flex items-center gap-2 mb-2">
                  {/* Upgraded to Shadcn Badge */}
                  <Badge variant="secondary" className="text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full">
                    {site.tone || "Minimalist"}
                  </Badge>
                </div>
                <CardTitle className="text-lg font-bold truncate">{site.brand_name}</CardTitle>
                <CardDescription className="text-xs font-semibold text-primary truncate">
                  {site.category}
                </CardDescription>
              </CardHeader>
              <CardContent className="pb-4">
                <p className="text-xs text-muted-foreground line-clamp-3 leading-relaxed">
                  {site.intro || "No description provided for this variant layout blueprint."}
                </p>
              </CardContent>
              <CardFooter className="border-t pt-4 bg-muted/30 flex justify-between items-center px-6 py-3">
                <span className="text-[11px] font-mono text-muted-foreground">
                  ID: {site.user_id ? site.user_id.slice(0, 8) : "anonymous"}
                </span>
                <Button 
                  size="sm" 
                  className="h-8 gap-1.5 text-xs font-medium"
                  onClick={() => setSelectedSite(site)}
                >
                  <Eye className="h-3.5 w-3.5" /> View Demo
                </Button>
              </CardFooter>
            </Card>
          ))}
        </div>
      </div>

      <Dialog open={selectedSite !== null} onOpenChange={(open) => !open && setSelectedSite(null)}>
        <DialogContent className="max-w-6xl w-[95vw] h-[90vh] flex flex-col p-0 overflow-hidden bg-background border gap-0">
          <DialogHeader className="p-4 border-b bg-muted/40 flex flex-col space-y-0.5 text-left">
            <DialogTitle className="text-sm font-bold text-foreground">
              {selectedSite?.brand_name}
            </DialogTitle>
            <CardDescription className="text-xs">
              {selectedSite?.category} • Theme: {selectedSite?.tone}
            </CardDescription>
          </DialogHeader>

          <div className="flex-1 overflow-hidden relative bg-muted/10 p-4">
            {selectedSite && (
              <SitePreview data={{ compiled_html: selectedSite.compiled_html }} />
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}