import json
import re
from typing import Optional, TypedDict
from langgraph.graph import StateGraph, END
from langchain_openai import ChatOpenAI
from schemas import WebsiteSchema, BrandRequest

class AgentState(TypedDict):
    request: BrandRequest
    generated_config: Optional[WebsiteSchema]
    retry_count: int
    feedback: str

def generate_site_node(state: AgentState):
    llm = ChatOpenAI(
        model="openai/gpt-oss-120b:free", 
        temperature=0.7
    )

    prompt = f"""
    You are an expert frontend developer and web designer.
    Your task is to output ONLY a valid, raw JSON object. Do not include markdown formatting like ```json.
    The JSON object must contain a single key called "compiled_html".
    The value of "compiled_html" must be a complete, self-contained landing page string starting with <!DOCTYPE html>.

    Brand Profile:
    - Name: {state['request'].brand_name}
    - Category: {state['request'].category}
    - Aesthetic / Tone: {state['request'].tone}
    - Brief Intro: {state['request'].intro}
    - Products/Services: {state['request'].products}

    Technical Requirements:
    1. Include the Tailwind CSS Play CDN script tag in the <head>: <script src="[https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4](https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4)"></script>
    2. Make sure it is beautiful, matches the tone, and contains fully built copy.
    3. Include interactive features inside standard vanilla <script> elements if necessary.
    4. CRITICAL FOR JSON VALIDATION: Escape all structural newlines inside your javascript text as literal text characters or collapse the code into continuous lines so it does not contain literal control code formatting breaks.
    5. CRITICAL FOR IFRAME PREVIEW: All links (<a> tags) MUST use href="#" or target="_blank". Do NOT use relative paths like href="/" or href="/contact" as they will break the sandbox preview.
    """
    
    if state.get("feedback"):
        prompt += f"\n\nCRITICAL EDITS REQUESTED: The user wants modifications based on this feedback: {state['feedback']}. Update the website structure or look accordingly."
    
    response = llm.invoke(prompt)
    
    if isinstance(response.content, str):
        raw_content = response.content
    else:
        raw_content = str(response.content)

    try:
        parsed_data = json.loads(raw_content)
    except json.JSONDecodeError:
        cleaned_content = re.sub(r'[\n\r\t]', ' ', raw_content)
        try:
            parsed_data = json.loads(cleaned_content)
        except Exception:
            parsed_data = {"compiled_html": "<h1>Generation Error</h1><p>The code structure generated by the model contained invalid characters. Please hit regenerate.</p>"}

    website_config = WebsiteSchema(compiled_html=str(parsed_data.get("compiled_html", "")))

    return {"generated_config": website_config, "retry_count": state["retry_count"] + 1}

workflow = StateGraph(AgentState)
workflow.add_node("generator", generate_site_node)
workflow.set_entry_point("generator")
workflow.add_edge("generator", END)

app_graph = workflow.compile()